#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Aaron K. Clark
#
# Every commit must DECLARE its authorship. Attribution is how we answer "which
# agent wrote this?" months later — the question that traces a regression back
# to the change that caused it. When the trailer is merely a habit it gets
# dropped silently: omind shipped 8.9.0 through 8.10.1 on five commits carrying
# no `Co-authored-by` at all, so two releases are permanently unattributable.
#
# The rule is a declaration, not a co-author requirement: a commit states either
# who helped write it, or that nobody did. Both are fine; silence is not.
#
#   Co-authored-by: <name> <email>   an agent (or person) co-wrote this
#   No-agent: true                   hand-written, no agent involved
#
# Usage:
#   check-attribution.sh --message-file <file>   # one message (commit-msg hook)
#   check-attribution.sh --range <base>..<head>  # a span of commits (CI)

set -eu

fail=0

check_message() {
    message=$1
    label=$2
    subject=$(printf '%s\n' "$message" | head -n 1)

    # Merges and reverts are generated by git/GitHub, not authored by anyone.
    case "$subject" in
        "Merge "* | "Revert "*) return 0 ;;
    esac

    if printf '%s\n' "$message" | grep -qiE '^Co-authored-by:[[:space:]]*[^[:space:]]'; then
        # A Claude co-author should carry the session link too, so the actual
        # transcript is reachable. Advisory only — older commits predate it.
        if printf '%s\n' "$message" | grep -qiE '^Co-authored-by:[[:space:]]*Claude' &&
            ! printf '%s\n' "$message" | grep -qiE '^Claude-Session:[[:space:]]*http'; then
            printf 'warning: %s: Claude co-author with no Claude-Session: trailer\n' \
                "$label" >&2
        fi
        return 0
    fi

    if printf '%s\n' "$message" | grep -qiE '^No-agent:[[:space:]]*true[[:space:]]*$'; then
        return 0
    fi

    printf 'error: %s: no authorship declared.\n' "$label" >&2
    printf '  Add ONE of these trailers to the commit message:\n' >&2
    printf '    Co-authored-by: Claude Opus 5 <noreply@anthropic.com>\n' >&2
    printf '    No-agent: true\n' >&2
    fail=1
    return 0
}

case "${1:---help}" in
    --message-file)
        [ $# -eq 2 ] || { echo "usage: $0 --message-file <file>" >&2; exit 2; }
        check_message "$(cat "$2")" "commit message"
        ;;
    --range)
        [ $# -eq 2 ] || { echo "usage: $0 --range <base>..<head>" >&2; exit 2; }
        for sha in $(git rev-list "$2"); do
            check_message "$(git log -1 --format=%B "$sha")" "$(git log -1 --format='%h %s' "$sha")"
        done
        ;;
    *)
        sed -n '4,20p' "$0" | sed 's/^# \{0,1\}//'
        exit 2
        ;;
esac

exit "$fail"
